<?php


namespace rednaowooextraproduct\core\Managers\SlateGenerator\Block;


use DOMDocument;
use rednaowooextraproduct\core\Managers\SlateGenerator\Core\NodeElementBase;
use rednaowooextraproduct\core\Managers\SlateGenerator\Core\SlateElementBase;

class SlateBody extends NodeElementBase
{

    public function Process()
    {
        $this->Node->SetAttribute("id",'RNEmailContainer');

        parent::Process(); // TODO: Change the autogenerated stub
    }


    public function PrepareNode()
    {
        $body=$this->Node->CreateAndAppendChild('tbody');
        $row=$body->CreateAndAppendChild('tr');
        $td=$row->CreateAndAppendChild('td');
        $this->NodeContainer=$td;
    }

    public function GetNodeName()
    {
        return 'table';
    }

}