/**
 * Docpen EHR Export Utilities
 * Formats SOAP notes for copy/paste into EHR, PDF export, and webhook
 */

import { jsPDF } from 'jspdf';

export interface SOAPNoteForExport {
  subjective?: string;
  objective?: string;
  assessment?: string;
  plan?: string;
  additionalNotes?: string;
}

export interface ExportContext {
  patientName?: string;
  sessionDate?: string;
  chiefComplaint?: string;
  consultantName?: string;
}

/**
 * Format SOAP note as plain text optimized for paste into EHR
 */
export function formatNoteForEHR(
  note: SOAPNoteForExport,
  context?: ExportContext
): string {
  const lines: string[] = [];

  if (context?.patientName) lines.push(`Patient: ${context.patientName}`);
  if (context?.sessionDate) lines.push(`Date: ${context.sessionDate}`);
  if (context?.chiefComplaint) lines.push(`Chief Complaint: ${context.chiefComplaint}`);
  if (context?.consultantName) lines.push(`Provider: ${context.consultantName}`);
  if (lines.length > 0) lines.push('');

  if (note.subjective) {
    lines.push('SUBJECTIVE:', note.subjective, '');
  }
  if (note.objective) {
    lines.push('OBJECTIVE:', note.objective, '');
  }
  if (note.assessment) {
    lines.push('ASSESSMENT:', note.assessment, '');
  }
  if (note.plan) {
    lines.push('PLAN:', note.plan, '');
  }
  if (note.additionalNotes) {
    lines.push('ADDITIONAL NOTES:', note.additionalNotes, '');
  }

  return lines.join('\n').trim();
}

/**
 * Generate PDF from SOAP note
 */
export function generatePDF(
  note: SOAPNoteForExport,
  context?: ExportContext
): Blob {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const margin = 20;
  let y = 20;
  const lineHeight = 6;
  const maxWidth = 170;

  const addText = (text: string, bold = false) => {
    doc.setFontSize(10);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    const lines = doc.splitTextToSize(text, maxWidth);
    lines.forEach((line: string) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += lineHeight;
    });
  };

  const addSection = (title: string, content?: string) => {
    if (!content) return;
    addText(title, true);
    y += 2;
    addText(content, false);
    y += 4;
  };

  if (context?.patientName) addText(`Patient: ${context.patientName}`);
  if (context?.sessionDate) addText(`Date: ${context.sessionDate}`);
  if (context?.chiefComplaint) addText(`Chief Complaint: ${context.chiefComplaint}`);
  if (context?.consultantName) addText(`Provider: ${context.consultantName}`);
  if (context?.patientName || context?.sessionDate) y += 4;

  addSection('SUBJECTIVE', note.subjective);
  addSection('OBJECTIVE', note.objective);
  addSection('ASSESSMENT', note.assessment);
  addSection('PLAN', note.plan);
  addSection('ADDITIONAL NOTES', note.additionalNotes);

  doc.text(
    'Generated by Docpen AI Scribe',
    margin,
    285
  );

  return doc.output('blob');
}

/**
 * Payload for webhook POST
 */
export function buildWebhookPayload(
  note: SOAPNoteForExport,
  context: ExportContext & { sessionId: string }
): Record<string, unknown> {
  return {
    sessionId: context.sessionId,
    patientName: context.patientName,
    sessionDate: context.sessionDate,
    chiefComplaint: context.chiefComplaint,
    consultantName: context.consultantName,
    soapNote: {
      subjective: note.subjective,
      objective: note.objective,
      assessment: note.assessment,
      plan: note.plan,
      additionalNotes: note.additionalNotes,
    },
    formattedText: formatNoteForEHR(note, context),
    exportedAt: new Date().toISOString(),
  };
}
