import { getCrmDb } from "@/lib/dal";
import { runExternalAdapters } from "@/lib/agent-command-center-adapters";
import { getLatestTrustMode } from "@/lib/agent-command-center";
import {
  evaluateAutonomyGate,
  getAutonomyControlPolicy,
} from "@/lib/agent-command-center-control";

type RunnerContext = {
  userId: string;
  industry: any;
};

type RunnerOptions = {
  enableExternal?: boolean;
  allowPaidLaunch?: boolean;
  apolloQuery?: string;
  socialMessage?: string;
  source?: "manual" | "cron" | "voice";
};

export async function runAgentCommandCenterCycle(
  ctx: RunnerContext,
  options: RunnerOptions = {},
) {
  const db = getCrmDb(ctx);
  const trust = await getLatestTrustMode(ctx);
  const control = await getAutonomyControlPolicy(ctx);

  const gate = evaluateAutonomyGate({
    policy: control.policy,
    module: "sales",
  });
  if (!gate.ok) {
    return {
      success: false,
      mode: trust.mode,
      blockedByOwnerControl: true,
      error: gate.reason,
    };
  }

  let candidates = await db.lead.findMany({
    where: {
      userId: ctx.userId,
      status: { in: ["NEW", "CONTACTED"] },
    },
    orderBy: { updatedAt: "asc" },
    take: 10,
    select: {
      id: true,
      contactPerson: true,
      businessName: true,
      email: true,
      phone: true,
      website: true,
    },
  });

  const external = await runExternalAdapters({
    db,
    userId: ctx.userId,
    trustMode: trust.mode,
    leads: candidates,
    options: {
      enableExternal: Boolean(options.enableExternal),
      allowPaidLaunch:
        Boolean(options.allowPaidLaunch) && control.policy.channels.ads,
      allowAds: control.policy.channels.ads,
      allowSocialPublish: control.policy.channels.social,
      apolloQuery: options.apolloQuery,
      socialMessage: options.socialMessage,
    },
  });

  candidates = await db.lead.findMany({
    where: {
      userId: ctx.userId,
      status: { in: ["NEW", "CONTACTED"] },
    },
    orderBy: { updatedAt: "asc" },
    take: 10,
    select: {
      id: true,
      contactPerson: true,
      businessName: true,
      email: true,
      phone: true,
      website: true,
    },
  });

  if (trust.mode === "crawl") {
    await Promise.all(
      candidates.map((lead) =>
        db.auditLog
          .create({
            data: {
              userId: ctx.userId,
              action: "SETTINGS_MODIFIED",
              severity: "LOW",
              entityType: "AUTONOMY_DRAFT_ACTION",
              entityId: crypto.randomUUID(),
              metadata: {
                leadId: lead.id,
                contactName:
                  lead.contactPerson || lead.businessName || "Unknown",
                proposedActions: [
                  "Create follow-up task",
                  "Draft personalized email",
                  "Draft SMS reminder",
                ],
                source: options.source || "manual",
                createdAt: new Date().toISOString(),
              },
              success: true,
            },
          })
          .catch(() => null),
      ),
    );

    return {
      success: true,
      mode: trust.mode,
      processedLeads: candidates.length,
      executed: 0,
      drafted: candidates.length,
      external,
      message: "Crawl mode: generated drafts only (no outbound actions).",
    };
  }

  let tasksCreated = 0;
  let emailsQueued = 0;
  let smsQueued = 0;

  const dayStart = new Date();
  dayStart.setHours(0, 0, 0, 0);
  const [todayTasks, todayEmails, todaySms] = await Promise.all([
    (db as any).task.count({
      where: { userId: ctx.userId, createdAt: { gte: dayStart } },
    }),
    (db as any).scheduledEmail.count({
      where: { userId: ctx.userId, createdAt: { gte: dayStart } },
    }),
    (db as any).scheduledSms.count({
      where: { userId: ctx.userId, createdAt: { gte: dayStart } },
    }),
  ]);

  for (const lead of candidates) {
    const livePolicy = (await getAutonomyControlPolicy(ctx)).policy;
    const loopGate = evaluateAutonomyGate({
      policy: livePolicy,
      module: "sales",
    });
    if (!loopGate.ok) break;
    if (tasksCreated + todayTasks >= control.policy.caps.dailyTasks) break;

    await (db as any).task.create({
      data: {
        userId: ctx.userId,
        leadId: lead.id,
        title: `Follow up with ${lead.contactPerson || lead.businessName || "lead"}`,
        description: "Auto-generated by Agent Command Center daily cycle.",
        priority: "HIGH",
        status: "TODO",
        autoCreated: true,
        aiSuggested: true,
        dueDate: new Date(Date.now() + 2 * 60 * 60 * 1000),
        tags: ["autonomy", "agent-command-center"],
      },
    });
    tasksCreated += 1;

    if (
      trust.mode === "run" &&
      lead.email &&
      control.policy.channels.email &&
      emailsQueued + todayEmails < control.policy.caps.dailyEmails
    ) {
      await (db as any).scheduledEmail.create({
        data: {
          userId: ctx.userId,
          leadId: lead.id,
          toEmail: lead.email,
          toName: lead.contactPerson || lead.businessName || null,
          subject: "Quick follow-up from our team",
          body: `Hi ${lead.contactPerson || "there"},\n\nFollowing up on your recent inquiry. We can help you move forward this week—reply with your preferred time and we will handle the rest.`,
          scheduledFor: new Date(Date.now() + 5 * 60 * 1000),
          status: "PENDING",
        },
      });
      emailsQueued += 1;
    }

    if (
      trust.mode === "run" &&
      lead.phone &&
      control.policy.channels.sms &&
      smsQueued + todaySms < control.policy.caps.dailySms
    ) {
      await (db as any).scheduledSms.create({
        data: {
          userId: ctx.userId,
          leadId: lead.id,
          toPhone: lead.phone,
          toName: lead.contactPerson || lead.businessName || null,
          message:
            "Quick follow-up from NexRel: we can get your setup moving today. Reply YES and we'll contact you immediately.",
          scheduledFor: new Date(Date.now() + 10 * 60 * 1000),
          status: "PENDING",
        },
      });
      smsQueued += 1;
    }
  }

  await db.auditLog.create({
    data: {
      userId: ctx.userId,
      action: "SETTINGS_MODIFIED",
      severity: "LOW",
      entityType: "NEXREL_AI_OPERATION",
      entityId: crypto.randomUUID(),
      metadata: {
        mode: "agent_command_center_cycle",
        trustMode: trust.mode,
        processedLeads: candidates.length,
        tasksCreated,
        emailsQueued,
        smsQueued,
        source: options.source || "manual",
        createdAt: new Date().toISOString(),
      },
      success: true,
    },
  });

  return {
    success: true,
    mode: trust.mode,
    processedLeads: candidates.length,
    tasksCreated,
    emailsQueued,
    smsQueued,
    external,
    message:
      trust.mode === "walk"
        ? "Walk mode: low-risk tasks auto-executed; outbound remains queued for approval."
        : "Run mode: follow-up tasks and outbound drafts were queued automatically.",
  };
}
